#!/bin/sh


# Install packages
	swd=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
	curl -fsSL https://raw.githubusercontent.com/NNBnh/bawkpack/master/bawkpack \
		&& echo 'Do you what to use this script?' && read -p '(y)es or (n)o: ' bawkpack_update
	case $bawkpack_update in
		'yes'|'y')
			curl -fsSL https://raw.githubusercontent.com/NNBnh/bawkpack/master/bawkpack > $swd/bawkpack
			chmod +x $swd/bawkpack
		;;
		'no'|'n')        ;;
		*)        exit 1 ;;
	esac
	[ ! -f "$swd/bawkpack" ] && echo 'Bawkpack is not found' && exit 1
	$swd/bawkpack "$swd/packageslist"


# Before symlink


# Symlink dotfiles
pwd="$PWD"
cd ..
stow -vt ~ home
sudo stow -vt / root
cd $pwd


# After symlink


exit 0
