#!/bin/sh

#    ____                    ___  __             __      __
#   / __/_ _____  ___ ____  / _ )/ /  ___  ___  / /____ / /________ ____
#  _\ \/ // / _ \/ -_) __/ / _  / _ \/ _ \/ _ \/ __(_-</ __/ __/ _ `/ _ \
# /___/\_,_/ .__/\__/_/   /____/_.__/\___/\___/\__/___/\__/_/  \_,_/ .__/
#         /_/                                                     /_/
	
# File:         super-bootstrap
# Description:  Bootstrap system that SuperB
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/super-bootstrap
# License:      GPLv3

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Values


# Start


exit 0
