#!/bin/sh

#    ___  ___           __
#   / _ )/ _ \___ _____/ /_____ ____ ____ ___
#  / _  / ___/ _ `/ __/  '_/ _ `/ _ `/ -_|_-<
# /____/_/   \_,_/\__/_/\_\\_,_/\_, /\__/___/
#                              /___/

# File:         bpackages
# Description:  Packages bootstrap that superB
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/bpackages
# License:      GPLv3

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Values
pwd="$PWD"
superboostrap_dir="${SUPERBOOTSTRAP_DIR:-$PWD}"
packages_file="$superboostrap_dir/bootstrap/packages"
packages_cache="${XDG_CACHE_HOME:-"$HOME/.cache"}/superboostrap"
mainpm=${SUPERBOOTSTRAP_MAINPM:-'APT'}


# Functions
install_packages() {
	if [ -f "$packages_file" ]; then
		awk '{gsub("#.*$", "");print}' "$packages_file" > "$packages_cache"

		                             pms="$mainpm"
		[ "$mainpm"  = 'Pacman' ] && pms="$pms AUR"
		                             pms="$pms Flatpak"
		[ "$mainpm" != 'XBPS'   ] && pms="$pms Snapcraft"

		for pm in $pms; do
			if [ -n "$(cat "$packages_cache")" ]; then

				case $pm in
					'Pacman')    pm_launcher='sudo pacman --sync --refresh --noconfirm --needed' ; pm_mark='PAC' ;;
					'APT')       pm_launcher='sudo apt install --assume-yes'                     ; pm_mark='APT' ;;
					'XBPS')      pm_launcher='sudo xbps-install --sync --yes'                    ; pm_mark='XBP' ;;
					'AUR')       pm_launcher='yay -Sy --nodiffmenu --save'                       ; pm_mark='AUR' ;; #FIXME
					'Flatpak')   pm_launcher='sudo flatpak install'                              ; pm_mark='FLA' ;; #FIXME
					'Snapcraft') pm_launcher='sudo snap install'                                 ; pm_mark='SNA' ;; #FIXME
				esac

				echo "Installing $pm Packages:"

				$pm_launcher $(cat "$packages_cache" | awk -v FPAT="$pm_mark:[^ ]+" 'NF{ print $1 }' | awk "{gsub(\"$pm_mark:\", \"\");print}")

				awk "!/$pm_mark:/" "$packages_cache" > "$packages_cache"
			fi
		done
	else
		echo "No packages list found, skip install packages."
	fi
}

load_config() {
	load_config_file="$superboostrap_dir/bootstrap/${1:-'setup'}"

	if [ -f "$load_config_file" ]; then
		echo "Loading $1 config:"
		$load_config_file
	else
		echo "No $1 file found, skip $1 config."
	fi
}

symlink_files() {
	symlink_dir="${1:-'home'}"
	target_dir="${2:-'$HOME'}"

	cd "$superboostrap_dir"

	if [ -d "$symlink_dir" ]; then
		echo "Symlink $1 directory:"

		while :; do
			${3:+'sudo'} stow --version --dir="$symlink_dir" --target="$target_dir" && break
			echo "Error, please resolve it then press ^d (ctrl+d)"
			$SHELL
		done
	else
		echo "No $1 directory found, skip $1 symlink."
	fi
	
	cd "$pwd"
}


# Start
install_packages
load_config setup
symlink_files home $HOME
symlink_files root / sudo
load_config extra


exit 0
