#!/bin/sh


# Install packages
DOTS=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
curl -fsSL https://raw.githubusercontent.com/NNBnh/bawkpack/master/bawkpack --create-dirs -o "$DOTS/bawkpack" && chmod +x "$DOTS/bawkpack"
"$DOTS/bawkpack" "$DOTS/packageslist"


# Before symlink


# Symlink dotfiles
stow -vt ~ home
sudo stow -vt / root


# After symlink


exit 0
