#!/bin/sh

# WARNING !!!
# Please skip to line 46 to start your config.
# Don't touch anything from this line to line 45
# if you don't know what you are doing.

install_packages() {
	"$DOTS/extra/bawkpack" "$DOTS/packageslist"
}

batch_symlink() {
	batch_symlink_directory="$1"
	batch_symlink_target="$2"

	[ -n "$TRASH_PATH" ] && mkdir -p "$TRASH_PATH"

	scan_directory "$batch_symlink_directory"
}

scan_directory() {
	[ -d "$1" ] || exit 1

	for file in "$1"/.* "$1"/*; do
		[ "$file" = "$1/." ] || [ "$file" = "$1/.." ] || [ "$file" = "$1/*" ] && continue

		target="$batch_symlink_target${file#$batch_symlink_directory}"

		if [ -e "$target" ]; then
			if [ -d "$target" ] && [ ! -h "$target" ]; then
				scan_directory "$file"
			else
				if [ -n "$TRASH_PATH" ]; then
					mv "$target" "$TRASH_PATH"
				else
					rm "$target"
				fi && ln -s "$file" "$target"
			fi
		else
			ln -s "$file" "$target"
		fi
	done
}


###############################################################################

#    ____    __
#   / __/__ / /___ _____
#  _\ \/ -_) __/ // / _ \
# /___/\__/\__/\_,_/ .__/
#                 /_/

# Add description here:
# > Hello World!
# > This is my setup script.


# Values
DOTS=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

# Get your environment variables if you have
[ -e "$DOTS/home/.config/env" ] && . "$DOTS/home/.config/env"

# Default order of steps
STEPS="${*:-install before home root after}"

# Uncomment this if you want to move conflict files to trash instead of delete it
#TRASH_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/Trash/files"


# Functions
symlink_home() {
	batch_symlink "$DOTS/home" "$HOME"

	# Use this if you want to batch symlink with bsymlink
	#bsymlink "$DOTS/home" "$HOME"

	# Use this if you want to batch symlink with stow (you must cd to the directory that contain this setup file)
	#stow -vt ~ home
}

symlink_root() {
	sudo batch_symlink "$DOTS/root" '/'

	# Use this if you want to batch symlink with bsymlink
	#sudo bsymlink "$DOTS/root" '/'

	# Use this if you want to batch symlink with stow (you must cd to the directory that contain this setup file)
	#sudo stow -vt / root
}

before_symlink() {
	# Remove files that may conflict when symlink dotfiles
	rm .bashrc

	# Remove conflicting items in $HOME/.config
	[ -d "$HOME/.config" ] && for config_directory_path in "$HOME/.config/."* "$HOME/.config/"*; do
		config_directory_name="${config_directory_path#$XDG_CONFIG_HOME/}"

		if [ "$config_directory_name" != '.' ] && [ "$config_directory_name" != '..' ] && [ -e "$HOME/dots/home/.config/$config_directory_name" ]; then
			rm "$config_directory_path"
		fi
	done

	# Create directories (to symlink files inside only, not the directory itself)
	mkdir "$HOME/.config" "$HOME/.local/share" "$HOME/.local/bin" "$HOME/.cache"
}

after_symlink() {
	# Change default shell
	chsh -s '/usr/bin/fish'

	# Enable firewall
	sudo ufw enable
}


# Start
for step in $STEPS; do
	case "$step" in
		'i'|'install') install_packages ;;
		'b'|'before')  before_symlink   ;;
		'h'|'home')    symlink_home     ;;
		'r'|'root')    symlink_root     ;;
		'a'|'after')   after_symlink    ;;
		*)             exit 1           ;;
	esac
done


exit 0
