#!/bin/sh

#     ____
#    / __ )            __                  __
#   / __  /__ __    __/ /__ ___  ___ _____/ /__
#  / /_/ / _ `/ |/|/ /  '_// _ \/ _ `/ __/  '_/
# /_____/\_,_/|__,__/_/\_\/ .__/\_,_/\__/_/\_\
#                        /_/

# File:         bawkpack
# Description:  Packages list installer that SuperB
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/bawkpack
# License:      GPLv3

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Values
WD=$PWD
BAWKPACK_LIST=${1:-$BAWKPACK_LIST}; [ ! -f "$BAWKPACK_LIST" ] && echo 'Packages list is not found' && exit 1
BAWKPACK_LOCAL="${XDG_DATA_HOME:-"$HOME/.local/share"}/bawkpack"

if type pacman; then
	PACKAGEMANAGER_MAIN='Pacman'
	sudo pacman --sync --sysupgrade --refresh --noconfirm --needed
elif type apt; then
	PACKAGEMANAGER_MAIN='APT'
	sudo apt update  --assume-yes
	sudo apt upgrade --assume-yes
elif type xbps-install; then
	PACKAGEMANAGER_MAIN='XBPS'
	sudo xbps-install --sync --yes --update
	sudo xbps-install --sync --yes void-repo-nonfree void-repo-multilib void-repo-multilib-nonfree void-repo-debug
else
	echo "Packages manager not found"
	exit 1
fi

PACKAGEMANAGER_ALL='Pacman APT XBPS'
PACKAGEMANAGER_NOT=${PACKAGEMANAGER_ALL#$PACKAGEMANAGER_MAIN}
                                          PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST $PACKAGEMANAGER_MAIN"
                                          PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST $PACKAGEMANAGER_NOT"
[ "$PACKAGEMANAGER_MAIN"  = 'Pacman' ] && PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST AUR"
                                          PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Flatpak"
[ "$PACKAGEMANAGER_MAIN" != 'XBPS'   ] && PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Snap"


# Functions
setup_aur() {
	echo "BAWKPACK: installing YAY"
	sudo pacman --sync --refresh --noconfirm --needed git base-devel
	git clone https://aur.archlinux.org/yay.git "$BAWKPACK_LOCAL/yay"
	cd "$BAWKPACK_LOCAL/yay" || exit 1
	makepkg -si
	cd "$WD" || exit 1
}

setup_flatpak() {
	echo "BAWKPACK: installing Flatpak"
	if   [ $PACKAGEMANAGER_MAIN = 'Pacman' ]; then sudo pacman --sync --refresh --noconfirm --needed flatpak
	elif [ $PACKAGEMANAGER_MAIN = 'APT'    ]; then sudo apt install --assume-yes flatpak gnome-software-plugin-flatpak
	elif [ $PACKAGEMANAGER_MAIN = 'XBPS'   ]; then sudo xbps-install --sync --yes flatpak
	fi

	flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
}

setup_snap() {
	echo "BAWKPACK: installing Snap"
	if   [ $PACKAGEMANAGER_MAIN = 'Pacman' ]; then
		sudo pacman --sync --refresh --noconfirm --needed git
		git clone https://aur.archlinux.org/snapd.git "$BAWKPACK_LOCAL/snap"
		cd "$BAWKPACK_LOCAL/snap" || exit 1
		makepkg -si
		cd "$WD" || exit 1
		sudo systemctl enable --now snapd.socket
		sudo ln -s /var/lib/snapd/snap /snap
	elif [ $PACKAGEMANAGER_MAIN = 'APT' ]; then
		sudo apt install --assume-yes snapd
	fi

	snap install core
}


# Start
bawkpack_process=$(sed -e 's/#.*$//g' "$BAWKPACK_LIST")

for packagemanager in $PACKAGEMANAGER_LIST; do
	if [ -n "$bawkpack_process" ]; then
		case $packagemanager in
			'Pacman')  packagemanager_command='sudo pacman --sync --refresh --noconfirm --needed'     ; packagemanager_mark='PAC:' ;;
			'APT')     packagemanager_command='sudo apt install --assume-yes'                         ; packagemanager_mark='APT:' ;;
			'XBPS')    packagemanager_command='sudo xbps-install --sync --yes'                        ; packagemanager_mark='XBP:' ;;
			'AUR')     packagemanager_command='yay -Sy --nodiffmenu --save --noconfirm'; setup_aur    ; packagemanager_mark='AUR:' ;;
			'Flatpak') packagemanager_command='sudo flatpak install'                   ; setup_flatpak; packagemanager_mark='FLA:' ;;
			'Snap')    packagemanager_command='sudo snap install'                      ; setup_snap   ; packagemanager_mark='SNA:' ;;
		esac

		packages_list=$(printf "$bawkpack_process" | sed -e "s/^.*$packagemanager_mark//g" -e 's/[[:space:]].*$//g')

		bawkpack_process=$(printf "$bawkpack_process" | sed -e "s/$packagemanager_mark//g")

		case "$PACKAGEMANAGER_NOT" in
			*$packagemanager*) ;;
			*)
				echo "BAWKPACK: installing $packagemanager Packages"
				$packagemanager_command $packages_list
			;;
		esac
	fi
done


exit 0 # 128!!!
