#!/bin/sh

#    ___                 ___      __
#   / _ )___ __ ____ _  / (_)__  / /__
#  / _  (_-</ // /  ' \/ / / _ \/  '_/
# /____/___/\_, /_/_/_/_/_/_//_/_/\_\
#          /___/

# File:         bsymlink
# Description:  Batch symlink tool that SuperB
# Author:       NNB
#               └─ https://github.com/NNBnh
# URL:          https://github.com/NNBnh/bsymlink
# License:      GPLv3

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.


# Values
DIRECTORY=$(realpath "${1:-$PWD}")
TARGET=$(realpath "${2:-$HOME}")
TRASH="${3:-${XDG_DATA_HOME:-$HOME/.local/share}/Trash/files}"


# Functions
scan_directory() {
	[ -d "$1" ] || exit 1

	for file in "$1"/.* "$1"/*; do
		[ "$file" = "$1/." ] || [ "$file" = "$1/.." ] || [ "$file" = "$1/*" ] && continue

		target="$TARGET${file#$DIRECTORY}"

		if [ -e "$target" ]; then
			if [ -d "$target" ] && [ ! -h "$target" ]; then
				scan_directory "$file"
			else
				mv "$target" "$TRASH/" && ln -s "$file" "$target"
			fi
		else
			ln -s "$file" "$target"
		fi
	done
}


# Start
mkdir -p "$TRASH"

scan_directory "$DIRECTORY"


exit 0
